services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: pytest
    depends_on:
      - postgres_db
    networks:
      - app_network

  postgres_db:
    image: postgres:17-alpine
    restart: always
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    labels:
      com.docker.compose.network: app_network

volumes:
  postgres_data:
