services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: andersen_todo_list
    env_file:
      - .env
    networks:
      - app_network
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

  postgres_db:
    image: postgres:17-alpine
    restart: always
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    labels:
      com.docker.compose.network: app_network

volumes:
  postgres_data:
